# Generated by Django 2.1.7 on 2019-06-01 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0023_auto_20190601_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('is_active', models.BooleanField()),
                ('course_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_1s', to='frontend.Course')),
                ('course_10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_10s', to='frontend.Course')),
                ('course_11', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_11s', to='frontend.Course')),
                ('course_12', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_12s', to='frontend.Course')),
                ('course_13', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_13s', to='frontend.Course')),
                ('course_14', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_14s', to='frontend.Course')),
                ('course_15', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_15s', to='frontend.Course')),
                ('course_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_2s', to='frontend.Course')),
                ('course_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_3s', to='frontend.Course')),
                ('course_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_4s', to='frontend.Course')),
                ('course_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_5s', to='frontend.Course')),
                ('course_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_6s', to='frontend.Course')),
                ('course_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_7s', to='frontend.Course')),
                ('course_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_8s', to='frontend.Course')),
                ('course_9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_9s', to='frontend.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('father_name', models.CharField(max_length=120)),
                ('mother_name', models.CharField(max_length=120)),
                ('dob', models.DateField()),
                ('aadhar', models.PositiveIntegerField()),
                ('corr_add', models.TextField()),
                ('perm_add', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=3)),
                ('nationality', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phn', models.PositiveIntegerField()),
                ('father_occupation', models.CharField(max_length=120)),
                ('father_income', models.CharField(choices=[('Income up to Rs. 2,50,000', 'Income up to Rs. 2,50,000'), ('Income from Rs. 2,50,000 - Rs. 5,00,000', 'Income from Rs. 2,50,000 - Rs. 5,00,000'), ('Income from Rs. 5,00,000 - 10,00,000', 'Income from Rs. 5,00,000 - 10,00,000'), ('Income more than Rs. 10,00,000', 'Income more than Rs. 10,00,000')], max_length=180)),
                ('roll_10', models.PositiveIntegerField()),
                ('aggregate_10', models.CharField(max_length=50)),
                ('pcm_10', models.CharField(max_length=50)),
                ('roll_12', models.PositiveIntegerField()),
                ('aggregate_12', models.CharField(max_length=50)),
                ('pcm_12', models.CharField(max_length=50)),
                ('roll_upsee', models.PositiveIntegerField()),
                ('gen_rank', models.PositiveIntegerField()),
                ('cat_rank', models.PositiveIntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='admission.Application')),
                ('branch_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_1s', to='frontend.Course')),
                ('branch_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_2s', to='frontend.Course')),
                ('branch_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_3s', to='frontend.Course')),
                ('branch_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_4s', to='frontend.Course')),
            ],
        ),
    ]
