# Generated by Django 2.1.7 on 2019-06-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pdf',
            field=models.FileField(default='', upload_to='pdf/application'),
            preserve_default=False,
        ),
    ]
