# Generated by Django 2.1.7 on 2019-06-02 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_application_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.PositiveIntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_number', to='admission.Application')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='application_no',
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='aadhar',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=3),
        ),
    ]
