# Generated by Django 2.1.7 on 2019-06-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_auto_20190602_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='aadhar',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('application', 'aadhar')},
        ),
    ]
