# Generated by Django 2.1.7 on 2019-06-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_auto_20190602_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='father_income',
            field=models.CharField(choices=[('Up to Rs. 2,50,000', 'Up to Rs. 2,50,000'), ('From Rs. 2,50,000 - Rs. 5,00,000', 'From Rs. 2,50,000 - Rs. 5,00,000'), ('From Rs. 5,00,000 - 10,00,000', 'From Rs. 5,00,000 - 10,00,000'), ('More than Rs. 10,00,000', 'More than Rs. 10,00,000')], max_length=180),
        ),
    ]
