# Generated by Django 2.1.7 on 2019-06-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_auto_20190602_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC/ST', 'SC/ST'), ('Minority', 'Minority')], default='OBC', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='father_income',
            field=models.CharField(choices=[('Up to Rs. 2,00,000', 'Up to Rs. 2,00,000'), ('From Rs. 2,00,000 - Rs. 5,00,000', 'From Rs. 2,00,000 - Rs. 5,00,000'), ('From Rs. 5,00,000 - 10,00,000', 'From Rs. 5,00,000 - 10,00,000'), ('More than Rs. 10,00,000', 'More than Rs. 10,00,000')], max_length=180),
        ),
    ]
