# Generated by Django 2.1.7 on 2019-05-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('contact_num', models.PositiveIntegerField()),
                ('qualification1', models.CharField(max_length=50)),
                ('qualification2', models.CharField(max_length=50)),
                ('qualification3', models.CharField(max_length=50)),
                ('field_of_interest', models.TextField()),
                ('experience', models.TextField()),
                ('pic', models.ImageField(upload_to='images/faculty')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
    ]
