# Generated by Django 2.1.7 on 2019-05-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='qualification2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='qualification3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
