# Generated by Django 2.1.7 on 2019-05-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField()),
                ('students', models.PositiveIntegerField()),
                ('area', models.PositiveIntegerField()),
                ('alumni', models.PositiveIntegerField()),
                ('recruiters', models.PositiveIntegerField()),
                ('students_placed', models.PositiveIntegerField()),
                ('years', models.PositiveIntegerField()),
            ],
        ),
    ]
