# Generated by Django 2.1.7 on 2019-05-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20190529_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/event')),
                ('details', models.TextField()),
                ('on_landing', models.BooleanField()),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
