# Generated by Django 2.1.7 on 2019-05-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_infrastructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField(unique=True)),
                ('text_above', models.TextField(blank=True)),
                ('bullet1', models.TextField(blank=True)),
                ('bullet2', models.TextField(blank=True)),
                ('bullet3', models.TextField(blank=True)),
                ('bullet4', models.TextField(blank=True)),
                ('bullet5', models.TextField(blank=True)),
                ('bullet6', models.TextField(blank=True)),
                ('bullet7', models.TextField(blank=True)),
                ('bullet8', models.TextField(blank=True)),
                ('bullet9', models.TextField(blank=True)),
                ('bullet10', models.TextField(blank=True)),
                ('text_below', models.TextField(blank=True)),
            ],
        ),
    ]
