# Generated by Django 2.1.7 on 2019-05-30 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_visionmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('contact_num', models.PositiveIntegerField()),
                ('qualification1', models.CharField(max_length=50)),
                ('qualification2', models.CharField(blank=True, max_length=50)),
                ('qualification3', models.CharField(blank=True, max_length=50)),
                ('field_of_interest', models.TextField()),
                ('experience', models.TextField()),
                ('pic', models.ImageField(upload_to='images/faculty')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='faculties', to='frontend.Department')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'ordering': ['pk'],
            },
        ),
    ]
