# Generated by Django 2.1.7 on 2019-05-30 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_department_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(default='', upload_to='images/department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lab',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='labs', to='frontend.Department'),
        ),
    ]
