# Generated by Django 2.1.7 on 2019-05-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_auto_20190531_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='images/training_placement')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
