# Generated by Django 2.1.7 on 2019-05-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('pdf', models.FileField(upload_to='pdf/syllabus')),
                ('course', models.ForeignKey(on_delete='models.CASCADE', related_name='syllabus', to='frontend.Course')),
            ],
        ),
    ]
