# Generated by Django 2.1.7 on 2019-06-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_auto_20190601_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='semester',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='exams', to='frontend.Semester'),
        ),
    ]
