# Generated by Django 2.1.7 on 2019-06-03 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_auto_20190601_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepdf',
            name='application_form',
        ),
    ]
